/*
-- Query: SELECT * FROM my_sprint_data
LIMIT 0, 1000

-- Date: 2020-02-19 11:43
*/
INSERT INTO `` (`index`,`Chips`,`Cost Price C`,`Weight C`,`Scale C`,`Quantity_C`,`Cooldrinks`,`Cost Price CD`,`Weight CD`,`Scale CD`,`Quantity_CD`,`Pies`,`Cost Price P`,`Weight P`,`Scale P`,`Quantity_P`,`Fruit`,`Cost Price F`,`Weight F`,`Scale F`,`Quantity_F`,`Cupcakes`,`Cost Price CC`,`Weight CC`,`Scale CC`,`Quantity_CC`,`Veggies`,`Cost Price V`,`Weight V`,`Scale V`,`Quantity_V`) VALUES (0,'Simba',170,300,'g','100','Coke',220,750,'ml','300','Steak',220,20,'Oz','170','Pear',50,1,'kg','300','vanilla',5,76,'g','','Potato',30,1,'kg','');
INSERT INTO `` (`index`,`Chips`,`Cost Price C`,`Weight C`,`Scale C`,`Quantity_C`,`Cooldrinks`,`Cost Price CD`,`Weight CD`,`Scale CD`,`Quantity_CD`,`Pies`,`Cost Price P`,`Weight P`,`Scale P`,`Quantity_P`,`Fruit`,`Cost Price F`,`Weight F`,`Scale F`,`Quantity_F`,`Cupcakes`,`Cost Price CC`,`Weight CC`,`Scale CC`,`Quantity_CC`,`Veggies`,`Cost Price V`,`Weight V`,`Scale V`,`Quantity_V`) VALUES (1,'Lays',180,300,'g','150','Fanta',200,750,'ml','250','Chicken',200,25,'Oz','250','Orange',60,1,'kg','350','chocolate',7,80,'g','','Spinach',20,1,'kg','');
INSERT INTO `` (`index`,`Chips`,`Cost Price C`,`Weight C`,`Scale C`,`Quantity_C`,`Cooldrinks`,`Cost Price CD`,`Weight CD`,`Scale CD`,`Quantity_CD`,`Pies`,`Cost Price P`,`Weight P`,`Scale P`,`Quantity_P`,`Fruit`,`Cost Price F`,`Weight F`,`Scale F`,`Quantity_F`,`Cupcakes`,`Cost Price CC`,`Weight CC`,`Scale CC`,`Quantity_CC`,`Veggies`,`Cost Price V`,`Weight V`,`Scale V`,`Quantity_V`) VALUES (2,'Frytos',140,300,'g','140','Stoney',210,250,'ml','240','Shepards Pie',210,27,'Oz','240','Grapes',80,1,'kg','340','Cuppuccino',8,83,'g','','Cabbage',30,1,'kg','');
INSERT INTO `` (`index`,`Chips`,`Cost Price C`,`Weight C`,`Scale C`,`Quantity_C`,`Cooldrinks`,`Cost Price CD`,`Weight CD`,`Scale CD`,`Quantity_CD`,`Pies`,`Cost Price P`,`Weight P`,`Scale P`,`Quantity_P`,`Fruit`,`Cost Price F`,`Weight F`,`Scale F`,`Quantity_F`,`Cupcakes`,`Cost Price CC`,`Weight CC`,`Scale CC`,`Quantity_CC`,`Veggies`,`Cost Price V`,`Weight V`,`Scale V`,`Quantity_V`) VALUES (3,'Bigcorn',130,300,'g','190','Dr Pepper',150,500,'ml','290','Apple Pie',150,20,'Oz','290','Devil Fruit',70,1,'kg','390','Blueberry',6,86,'g','','Broccoli',20,1,'kg','');
INSERT INTO `` (`index`,`Chips`,`Cost Price C`,`Weight C`,`Scale C`,`Quantity_C`,`Cooldrinks`,`Cost Price CD`,`Weight CD`,`Scale CD`,`Quantity_CD`,`Pies`,`Cost Price P`,`Weight P`,`Scale P`,`Quantity_P`,`Fruit`,`Cost Price F`,`Weight F`,`Scale F`,`Quantity_F`,`Cupcakes`,`Cost Price CC`,`Weight CC`,`Scale CC`,`Quantity_CC`,`Veggies`,`Cost Price V`,`Weight V`,`Scale V`,`Quantity_V`) VALUES (4,'Doritos',190,300,'g','150','MountDew',170,500,'ml','250','Chicken Mushroom',170,34,'Oz','250','PawPaw',95,1,'kg','350','Bran',5,87,'g','','Cellery',50,1,'kg','');
